### ISSUE TITLE
[Bug] Feature cant be used in stable release channel

### ISSUE THREAD

**Issue by Highstead** [pseudomuto/rejson#2]
Tried following your installation instructions.  

```
cargo install rejson
......
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/highstead/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rejson-0.2.0/src/lib.rs:2:1
  |
2 | #![feature(trait_alias)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
```

**Comment by pseudomuto** [comment]
Yeah, I know 😄  Honestly, I'm only using nightly for a convenience trait alias (absolutely not necessary) and some unstable rustfmt options. I'll see what I can do to address this.

For now, `cargo +nightly install rejson` seems to work

**Comment by pseudomuto** [comment]
I've added the prebuilt binaries to the releases now so that you don't need to compile rejson to install it. I updated the installation instructions in the README with details on how to install it without cargo.

<https://github.com/pseudomuto/rejson/releases/latest>
